version: "3.8"
services:
  tg-bot:
    build: .
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - DATABASE=$DATABASE
    volumes:
      - ./database:/usr/src/app/database
      - ./img:/usr/src/app/img
